#!/usr/bin/env python
#
# makesymlinks
# Copyright 2010 Gustavo Franco <stratus@acm.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing sharepermissions and
# limitations under the License.

RCS = ['.vimrc', '.gitconfig', '.screenrc']

import os
import sys


def makesymlinks(repo_path):
  homedir = os.getenv('HOME')
  if not homedir:
    print 'Cannot define HOME environment variable, please set.'
    sys.exit(1)

  for rc in RCS:
    local_rc = '%s/%s' % (homedir, rc)
    repo_rc = '%s/%s' % (repo_path, rc)
    if os.path.islink(local_rc):
      print '%s is a symlink already, skipping.' % local_rc
    elif os.path.isdir(local_rc):
      print '%s is a directory, skipping.' % local_rc
    else:
      if os.path.isfile(local_rc):
        os.rename(local_rc, '%s.bak') % local_rc
      print 'Attempting to symlink %s to %s' % (local_rc, repo_rc)
      os.symlink(repo_rc, local_rc)


if __name__ == '__main__':
  if not sys.argv[1:]:
    print 'Usage: makesymlinks <path to dotrc.git local copy>'
    sys.exit(2)

  makesymlinks(sys.argv[1])
