#!/usr/bin/env python3
#
# makesymlinks
# Copyright 2024 Gustavo Franco <stratus@acm.org>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys
import os
import subprocess
import logging
DEBUG = False

TMUX_REPO = 'https://github.com/gpakosz/.tmux.git'


def setup_tmux(logger, homedir):
    """Bootstrap gpakosz/.tmux if not already cloned."""
    tmux_dir = os.path.join(homedir, '.tmux')
    tmux_conf = os.path.join(homedir, '.tmux.conf')

    if not os.path.isdir(tmux_dir):
        logger.info('Cloning %s into %s', TMUX_REPO, tmux_dir)
        try:
            subprocess.run(
                ['git', 'clone', TMUX_REPO, tmux_dir],
                check=True, capture_output=True, text=True)
        except (subprocess.CalledProcessError, FileNotFoundError) as e:
            logger.error('Failed to clone tmux repo: %s', e)
            return
    else:
        logger.info('%s already exists, skipping clone.', tmux_dir)

    # Ensure ~/.tmux.conf -> ~/.tmux/.tmux.conf (upstream's expected layout)
    upstream_conf = os.path.join(tmux_dir, '.tmux.conf')
    if os.path.islink(tmux_conf):
        logger.info('%s is a symlink already, skipping.', tmux_conf)
    elif os.path.isfile(tmux_conf):
        logger.info('Renaming %s to %s.bak', tmux_conf, tmux_conf)
        os.rename(tmux_conf, tmux_conf + '.bak')
        os.symlink(upstream_conf, tmux_conf)
        logger.info('Symlinked %s -> %s', tmux_conf, upstream_conf)
    else:
        os.symlink(upstream_conf, tmux_conf)
        logger.info('Symlinked %s -> %s', tmux_conf, upstream_conf)


def makesymlinks(logger):
    homedir = os.getenv('HOME')
    if not homedir:
        print('Cannot define HOME environment variable, please set.')
        sys.exit(1)
    logger.debug('homedir is set to %s', homedir)

    rcs_path = os.getenv('RCS_PATH')
    if not rcs_path:
        rcs_path = os.path.join(os.getcwd(), 'rcs')
    logger.debug('rcs_path is set to %s', rcs_path)

    setup_tmux(logger, homedir)

    for rc in os.listdir(rcs_path):
        repo_rc = os.path.join(rcs_path, rc)
        if not os.path.isfile(repo_rc):
            logger.info('%s is not a regular file, skipping.', repo_rc)
            continue
        local_rc = os.path.join(homedir, rc)
        if os.path.islink(local_rc):
            logger.info('%s is a symlink already, skipping.', local_rc)
        elif os.path.isdir(local_rc):
            logger.info('%s is a directory, skipping.', local_rc)
        else:
            try:
                if os.path.isfile(local_rc):
                    logger.debug('Renaming %s to %s.bak', local_rc, local_rc)
                    os.rename(local_rc, local_rc + '.bak')
                logger.info(
                    'Attempting to symlink %s to %s',
                    local_rc,
                    repo_rc)
                os.symlink(repo_rc, local_rc)
            except OSError as e:
                logger.error('Failed to link %s -> %s: %s', local_rc, repo_rc, e)


if __name__ == '__main__':
    logging.basicConfig(level=logging.INFO)
    logger = logging.getLogger('makesymlinks')
    if DEBUG:
        logger.setLevel(logging.DEBUG)
    makesymlinks(logger)
